spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig
          searchPaths: respo
          username: miles02@163.com
          password:
      label: master
#        native:
#          search-locations: classpath:/shared

#  profiles:
#    active: native
  application:
    name: config-server

server:
  port: 8768

eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/